# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-01-31 06:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StudentAnswerApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subquestion',
            name='kind',
        ),
        migrations.AddField(
            model_name='subquestion',
            name='auto_correction',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='answer',
            name='created_date_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='examination',
            name='created_date_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='examinationanswerpaper',
            name='created_date_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='examinationpaper',
            name='created_date_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='personinformation',
            name='gender',
            field=models.NullBooleanField(choices=[(None, '\u4fdd\u5bc6'), (True, '\u7537'), (False, '\u5973')], default=None),
        ),
        migrations.AlterField(
            model_name='question',
            name='created_date_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='subquestion',
            name='standard_answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentAnswerApp.SubAnswer'),
        ),
    ]
