# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-02-01 09:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StudentAnswerApp', '0002_auto_20180131_1459'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Disccussion',
            new_name='Discussion',
        ),
    ]
