# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-02-04 11:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StudentAnswerApp', '0003_auto_20180201_1746'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personinformation',
            old_name='account',
            new_name='user',
        ),
    ]
