# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-02-04 12:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StudentAnswerApp', '0004_auto_20180204_1937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personinformation',
            name='id',
        ),
        migrations.AlterField(
            model_name='personinformation',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='person_information', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
