# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-02-11 08:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StudentAnswerApp', '0005_auto_20180204_2007'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='subanswer',
            name='belong_to_Answer',
        ),
        migrations.AddField(
            model_name='subanswer',
            name='belong_to_answer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='StudentAnswerApp.Answer', verbose_name='Belong To Answer'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='created_date_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created Date Time'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentAnswerApp.Question', verbose_name='Question'),
        ),
        migrations.AlterField(
            model_name='class',
            name='class_examination_papers',
            field=models.ManyToManyField(to='StudentAnswerApp.ExaminationPaper', verbose_name='Class Examination Papers'),
        ),
        migrations.AlterField(
            model_name='class',
            name='class_examinations',
            field=models.ManyToManyField(to='StudentAnswerApp.Examination', verbose_name='Class Examintions'),
        ),
        migrations.AlterField(
            model_name='class',
            name='class_members',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Class Member'),
        ),
        migrations.AlterField(
            model_name='class',
            name='class_questions',
            field=models.ManyToManyField(to='StudentAnswerApp.Question', verbose_name='Class Questions'),
        ),
        migrations.AlterField(
            model_name='class',
            name='created_date_time',
            field=models.DateTimeField(verbose_name='Created Date Time'),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='content',
            field=models.TextField(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='created_date_time',
            field=models.DateTimeField(verbose_name='Created Date Time'),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='related_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentAnswerApp.Question', verbose_name='Related Question'),
        ),
        migrations.AlterField(
            model_name='examination',
            name='begin_date_time',
            field=models.DateTimeField(verbose_name='Begin Date Time'),
        ),
        migrations.AlterField(
            model_name='examination',
            name='can_submit_num',
            field=models.PositiveSmallIntegerField(verbose_name='Can Submit Number'),
        ),
        migrations.AlterField(
            model_name='examination',
            name='created_date_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created Date Time'),
        ),
        migrations.AlterField(
            model_name='examination',
            name='end_date_time',
            field=models.DateTimeField(verbose_name='End Date Time'),
        ),
        migrations.AlterField(
            model_name='examination',
            name='examination_paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentAnswerApp.ExaminationPaper', verbose_name='Examinaton Paper'),
        ),
        migrations.AlterField(
            model_name='examination',
            name='kind',
            field=models.CharField(max_length=100, verbose_name='Kind'),
        ),
        migrations.AlterField(
            model_name='examination',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Examination'),
        ),
        migrations.AlterField(
            model_name='examination',
            name='time_length',
            field=models.DurationField(verbose_name='Time Length'),
        ),
        migrations.AlterField(
            model_name='examinationanswer',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentAnswerApp.Answer', verbose_name='Answer'),
        ),
        migrations.AlterField(
            model_name='examinationanswer',
            name='belong_to_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentAnswerApp.ExaminationAnswerGroup', verbose_name='Belong To Group'),
        ),
        migrations.AlterField(
            model_name='examinationanswer',
            name='gaven_score',
            field=models.PositiveSmallIntegerField(verbose_name='Gaven Score'),
        ),
        migrations.AlterField(
            model_name='examinationanswer',
            name='group_order_number',
            field=models.PositiveSmallIntegerField(verbose_name='Group Order Number'),
        ),
        migrations.AlterField(
            model_name='examinationanswergroup',
            name='belong_to_answer_paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentAnswerApp.ExaminationAnswerPaper', verbose_name='Examintion Answer Group'),
        ),
        migrations.AlterField(
            model_name='examinationanswergroup',
            name='gaven_total_score',
            field=models.PositiveSmallIntegerField(verbose_name='Gaven Total Score'),
        ),
        migrations.AlterField(
            model_name='examinationanswergroup',
            name='group_order_number',
            field=models.PositiveSmallIntegerField(verbose_name='Group Order Number'),
        ),
        migrations.AlterField(
            model_name='examinationanswerpaper',
            name='created_date_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created Date Time'),
        ),
        migrations.AlterField(
            model_name='examinationanswerpaper',
            name='examination_paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentAnswerApp.ExaminationPaper', verbose_name='Examination Paper'),
        ),
        migrations.AlterField(
            model_name='examinationanswerpaper',
            name='gaven_total_score',
            field=models.PositiveSmallIntegerField(verbose_name='Gaven Total Score'),
        ),
        migrations.AlterField(
            model_name='examinationpaper',
            name='accessible_groups',
            field=models.ManyToManyField(to='auth.Group', verbose_name='Accessible Groups'),
        ),
        migrations.AlterField(
            model_name='examinationpaper',
            name='created_date_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created Date Time'),
        ),
        migrations.AlterField(
            model_name='examinationpaper',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='examinationpaper',
            name='total_score',
            field=models.PositiveSmallIntegerField(verbose_name='Total Score'),
        ),
        migrations.AlterField(
            model_name='examinationquestion',
            name='belong_to_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentAnswerApp.ExaminationQuestionGroup', verbose_name='Belong To Group'),
        ),
        migrations.AlterField(
            model_name='examinationquestion',
            name='order_number',
            field=models.PositiveSmallIntegerField(verbose_name='Order Number'),
        ),
        migrations.AlterField(
            model_name='examinationquestion',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentAnswerApp.Question', verbose_name='Question'),
        ),
        migrations.AlterField(
            model_name='examinationquestion',
            name='score',
            field=models.PositiveSmallIntegerField(verbose_name='Score'),
        ),
        migrations.AlterField(
            model_name='examinationquestiongroup',
            name='belong_to_examination_paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentAnswerApp.ExaminationPaper', verbose_name='Belong To Examination Paper'),
        ),
        migrations.AlterField(
            model_name='examinationquestiongroup',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='examinationquestiongroup',
            name='group_order_number',
            field=models.PositiveSmallIntegerField(verbose_name='Group Order Number'),
        ),
        migrations.AlterField(
            model_name='examinationquestiongroup',
            name='total_score',
            field=models.PositiveSmallIntegerField(verbose_name='Total Score'),
        ),
        migrations.AlterField(
            model_name='personinformation',
            name='age',
            field=models.PositiveSmallIntegerField(verbose_name='Age'),
        ),
        migrations.AlterField(
            model_name='personinformation',
            name='gender',
            field=models.NullBooleanField(choices=[(None, 'secrecy'), (True, 'male'), (False, 'female')], default=None, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='personinformation',
            name='head_portrait',
            field=models.ImageField(upload_to=b'', verbose_name='Head Portrait'),
        ),
        migrations.AlterField(
            model_name='personinformation',
            name='nickname',
            field=models.CharField(blank=True, max_length=20, verbose_name='Nickname'),
        ),
        migrations.AlterField(
            model_name='question',
            name='accessible_groups',
            field=models.ManyToManyField(to='auth.Group', verbose_name='Accessible Groups'),
        ),
        migrations.AlterField(
            model_name='question',
            name='content_description',
            field=models.TextField(verbose_name='Content Description'),
        ),
        migrations.AlterField(
            model_name='question',
            name='created_date_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created Date Time'),
        ),
        migrations.AlterField(
            model_name='question',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creator'),
        ),
        migrations.AlterField(
            model_name='subanswer',
            name='content',
            field=models.TextField(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='subanswer',
            name='order_number',
            field=models.PositiveSmallIntegerField(verbose_name='Order Number'),
        ),
        migrations.AlterField(
            model_name='subexaminationanswer',
            name='belong_to_examination_answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentAnswerApp.ExaminationAnswer', verbose_name='Belong To Examintion Answer'),
        ),
        migrations.AlterField(
            model_name='subexaminationanswer',
            name='order_number',
            field=models.PositiveSmallIntegerField(verbose_name='Order Number'),
        ),
        migrations.AlterField(
            model_name='subexaminationanswer',
            name='score',
            field=models.PositiveSmallIntegerField(verbose_name='Score'),
        ),
        migrations.AlterField(
            model_name='subexaminationanswer',
            name='sub_answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentAnswerApp.SubAnswer', verbose_name='Sub Answer'),
        ),
        migrations.AlterField(
            model_name='subexaminationquestion',
            name='belong_to_examination_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentAnswerApp.ExaminationQuestion', verbose_name='Belong To Examination Question'),
        ),
        migrations.AlterField(
            model_name='subexaminationquestion',
            name='order_number',
            field=models.PositiveSmallIntegerField(verbose_name='Order Number'),
        ),
        migrations.AlterField(
            model_name='subexaminationquestion',
            name='score',
            field=models.PositiveSmallIntegerField(verbose_name='Score'),
        ),
        migrations.AlterField(
            model_name='subexaminationquestion',
            name='sub_Question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentAnswerApp.SubQuestion', verbose_name='SubQuestion'),
        ),
        migrations.AlterField(
            model_name='subquestion',
            name='auto_correction',
            field=models.BooleanField(default=False, verbose_name='Is Auto Correction'),
        ),
        migrations.AlterField(
            model_name='subquestion',
            name='belong_to_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentAnswerApp.Question', verbose_name='Belong To Queston'),
        ),
        migrations.AlterField(
            model_name='subquestion',
            name='category',
            field=models.CharField(max_length=50, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='subquestion',
            name='content',
            field=models.TextField(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='subquestion',
            name='order_number',
            field=models.PositiveSmallIntegerField(verbose_name='Order Number'),
        ),
        migrations.AlterField(
            model_name='subquestion',
            name='related_knowledge_point',
            field=models.CharField(max_length=50, verbose_name='Related Knowledge Point'),
        ),
        migrations.AlterField(
            model_name='subquestion',
            name='standard_answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentAnswerApp.SubAnswer', verbose_name='Standard Answer'),
        ),
        migrations.AlterField(
            model_name='subquestion',
            name='subject',
            field=models.CharField(max_length=50, verbose_name='Subject'),
        ),
        migrations.AlterField(
            model_name='userexaminationrecord',
            name='begin_date_time',
            field=models.DateTimeField(verbose_name='Begin Date Time'),
        ),
        migrations.AlterField(
            model_name='userexaminationrecord',
            name='end_date_time',
            field=models.DateTimeField(verbose_name='End Date Time'),
        ),
        migrations.AlterField(
            model_name='userexaminationrecord',
            name='examination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentAnswerApp.Examination', verbose_name='Examination'),
        ),
        migrations.AlterField(
            model_name='userexaminationrecord',
            name='examination_answer_paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentAnswerApp.ExaminationAnswerPaper', verbose_name='Examination Answer Paper'),
        ),
        migrations.AlterField(
            model_name='userexaminationrecord',
            name='submit_num',
            field=models.PositiveSmallIntegerField(verbose_name='Submit Number'),
        ),
    ]
