# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-06 05:46
from __future__ import unicode_literals

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('StudentAnswerApp', '0006_auto_20180211_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personinformation',
            name='head_portrait',
            field=imagekit.models.fields.ProcessedImageField(upload_to=b'', verbose_name='Head Portrait'),
        ),
    ]
