# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-06 05:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('StudentAnswerApp', '0007_auto_20180306_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_classes', to=settings.AUTH_USER_MODEL),
        ),
    ]
