# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-08 09:19
from __future__ import unicode_literals

from django.db import migrations
import tagging.fields


class Migration(migrations.Migration):

    dependencies = [
        ('StudentAnswerApp', '0008_class_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='tags',
            field=tagging.fields.TagField(blank=True, max_length=255),
        ),
    ]
