# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-11 12:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StudentAnswerApp', '0009_question_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': 'Answer'},
        ),
        migrations.AlterModelOptions(
            name='class',
            options={'verbose_name': 'Class'},
        ),
        migrations.AlterModelOptions(
            name='examination',
            options={'verbose_name': 'Examination'},
        ),
        migrations.AlterModelOptions(
            name='examinationanswer',
            options={'verbose_name': 'Examination Answer'},
        ),
        migrations.AlterModelOptions(
            name='examinationanswergroup',
            options={'verbose_name': 'Examination Answer Group'},
        ),
        migrations.AlterModelOptions(
            name='examinationanswerpaper',
            options={'verbose_name': 'Examination Answer Paper'},
        ),
        migrations.AlterModelOptions(
            name='examinationpaper',
            options={'verbose_name': 'Examination Paper'},
        ),
        migrations.AlterModelOptions(
            name='examinationquestion',
            options={'verbose_name': 'Examination Question'},
        ),
        migrations.AlterModelOptions(
            name='examinationquestiongroup',
            options={'verbose_name': 'Examination Question Group'},
        ),
        migrations.AlterModelOptions(
            name='personinformation',
            options={'verbose_name': 'Person Information'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Question'},
        ),
        migrations.AlterModelOptions(
            name='subanswer',
            options={'verbose_name': 'Sub Answer'},
        ),
        migrations.AlterModelOptions(
            name='subexaminationquestion',
            options={'verbose_name': 'Sub Examination Question'},
        ),
        migrations.AlterModelOptions(
            name='subquestion',
            options={'verbose_name': 'Sub Question'},
        ),
        migrations.AlterModelOptions(
            name='userexaminationrecord',
            options={'verbose_name': 'User Examination Record'},
        ),
        migrations.RemoveField(
            model_name='personinformation',
            name='head_portrait',
        ),
        migrations.RemoveField(
            model_name='subquestion',
            name='category',
        ),
        migrations.RemoveField(
            model_name='subquestion',
            name='related_knowledge_point',
        ),
        migrations.RemoveField(
            model_name='subquestion',
            name='subject',
        ),
        migrations.AddField(
            model_name='subquestion',
            name='correction_rate',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Correction Rate'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='creator',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='class',
            name='class_examination_papers',
            field=models.ManyToManyField(null=True, to='StudentAnswerApp.ExaminationPaper', verbose_name='Class Examination Papers'),
        ),
        migrations.AlterField(
            model_name='class',
            name='class_examinations',
            field=models.ManyToManyField(null=True, to='StudentAnswerApp.Examination', verbose_name='Class Examintions'),
        ),
        migrations.AlterField(
            model_name='class',
            name='class_members',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL, verbose_name='Class Member'),
        ),
        migrations.AlterField(
            model_name='class',
            name='class_questions',
            field=models.ManyToManyField(null=True, to='StudentAnswerApp.Question', verbose_name='Class Questions'),
        ),
        migrations.AlterField(
            model_name='class',
            name='created_date_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created Date Time'),
        ),
        migrations.AlterField(
            model_name='class',
            name='creator',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_classes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='examination',
            name='creator',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='examinationanswerpaper',
            name='creator',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='examinationpaper',
            name='accessible_groups',
            field=models.ManyToManyField(null=True, to='auth.Group', verbose_name='Accessible Groups'),
        ),
        migrations.AlterField(
            model_name='examinationpaper',
            name='creator',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='personinformation',
            name='user',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='person_information', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='question',
            name='accessible_groups',
            field=models.ManyToManyField(null=True, to='auth.Group', verbose_name='Accessible Groups'),
        ),
        migrations.AlterField(
            model_name='question',
            name='creator',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creator'),
        ),
    ]
