# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-12 15:02
from __future__ import unicode_literals

from django.db import migrations, models
import tagging.fields


class Migration(migrations.Migration):

    dependencies = [
        ('StudentAnswerApp', '0011_auto_20180312_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='name',
            field=models.CharField(default=b'class', max_length=50, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='class',
            name='tags',
            field=tagging.fields.TagField(blank=True, max_length=255),
        ),
    ]
