# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-24 07:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('StudentAnswerApp', '0013_auto_20180319_2224'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('object_id', models.PositiveIntegerField()),
                ('sum', models.PositiveIntegerField(default=0)),
                ('tag', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['-created_date_time'], 'verbose_name': 'Answer'},
        ),
        migrations.AlterModelOptions(
            name='class',
            options={'ordering': ['-created_date_time'], 'verbose_name': 'Class'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-created_date_time'], 'verbose_name': 'Question'},
        ),
        migrations.AddField(
            model_name='class',
            name='description',
            field=models.TextField(blank=True, default=b'', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='class',
            name='name',
            field=models.CharField(default=b'class', max_length=50, verbose_name='Name'),
        ),
    ]
