# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-26 11:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StudentAnswerApp', '0015_auto_20180326_1829'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='favorite_user',
            new_name='favorite_users',
        ),
    ]
